# Generated by Django 3.2 on 2021-05-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_instagram_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='facebook_handle',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_handle',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
