# Generated by Django 3.2 on 2021-06-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210527_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='consultation',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
