# Generated by Django 3.2 on 2021-06-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='reviewed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
