# Generated by Django 3.2 on 2021-06-14 11:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userprofile_consultation'),
        ('checkout', '0006_orderlineitem_reviewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(blank=True, max_length=120, null=True)),
                ('review', models.TextField(blank=True, max_length=500, null=True)),
                ('review_stars', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('date_reviewed', models.DateField(auto_now=True)),
                ('order_line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_reviewed', to='checkout.orderlineitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_user', to='profiles.userprofile')),
            ],
        ),
    ]
