# Generated by Django 3.2 on 2021-06-14 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='reviewed',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
