# Generated by Django 3.2 on 2021-06-14 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userprofile_consultation'),
        ('checkout', '0008_auto_20210614_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_line_items', to='profiles.userprofile'),
        ),
    ]
