# Generated by Django 3.2 on 2021-06-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_orderlineitem_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='product_name',
            field=models.CharField(default='product_name', max_length=250),
            preserve_default=False,
        ),
    ]
