# Generated by Django 3.2 on 2021-06-26 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_orderlineitem_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product_name',
        ),
    ]
