# Generated by Django 3.2 on 2021-07-06 17:24

from django.db import migrations, models
import lionize.validations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_remove_orderlineitem_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[lionize.validations.validate_phone_number]),
        ),
    ]
