# Generated by Django 3.2 on 2021-04-28 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='image',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='image_url',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
