# Generated by Django 3.2 on 2021-07-01 13:38

from django.db import migrations, models
import lionize.validations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_in_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=500, validators=[lionize.validations.validate_min_length_50]),
        ),
        migrations.AlterField(
            model_name='product',
            name='friendly_name',
            field=models.CharField(max_length=254, validators=[lionize.validations.validate_min_length_2]),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=254, validators=[lionize.validations.validate_min_length_2]),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_title',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
