# Generated by Django 3.2 on 2021-07-06 17:24

from django.db import migrations, models
import lionize.validations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210701_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=500, validators=[lionize.validations.validate_min_length_50, lionize.validations.validate_text_input]),
        ),
        migrations.AlterField(
            model_name='product',
            name='friendly_name',
            field=models.CharField(max_length=254, validators=[lionize.validations.validate_min_length_2, lionize.validations.validate_text_input]),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=254, validators=[lionize.validations.validate_min_length_2, lionize.validations.validate_text_input]),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(max_length=500, null=True, validators=[lionize.validations.validate_min_length_20]),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_title',
            field=models.CharField(max_length=120, null=True, validators=[lionize.validations.validate_min_length_2]),
        ),
    ]
